### ISSUE TITLE
Creating an app and running in production contains errors

### ISSUE THREAD

**Issue by dishad** [rooseveltframework/generator-roosevelt#179]
Using a newly created roosevelt app with a standard configuration, the homepage will not load correctly in production mode because of missing .js and .css files errors reported by the console.

**Comment by lannonbr** [comment]
So this seems to be not a bug but rather a feature.

There is a `alwaysHostPublic` field that is used to expose the `public/` folder to the Roosevelt server. By default this is set to false but can be turned on with either the `--host-public`, `--statics` or `-s` command line arg, or setting `alwaysHostPublic` to true in the configs.

Here's the docs for further reading on the public folder params: https://github.com/rooseveltframework/roosevelt#public-folder-parameters
